name: "Rust Test Suite"

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main", "wip/**" ]

jobs:
  unittest:
    name: "Unittest - rust-${{ matrix.rust }}@${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        rust: ["nightly", "stable"]

    steps:
    - name: "Fetch Sources"
      uses: actions/checkout@v3
    - name: "Install Rust Components"
      run: rustup default "${{ matrix.rust }}"
    - name: "Build Project"
      run: cargo build --verbose --all-targets
    - name: "Run Tests"
      run: cargo test --verbose
